// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFNk8Xo4akgLh7ypLy4Gy10eyO77BUR-Y',
    appId: '1:63018309040:web:b41f057e20743c29007275',
    messagingSenderId: '63018309040',
    projectId: 'finyx-99abc',
    authDomain: 'finyx-99abc.firebaseapp.com',
    storageBucket: 'finyx-99abc.firebasestorage.app',
    measurementId: 'G-SNKZ2TNWD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuy5G29-PvEo4ocOcaXJX_OdPwA7a4aBc',
    appId: '1:63018309040:android:c96b6ec03e91a1a8007275',
    messagingSenderId: '63018309040',
    projectId: 'finyx-99abc',
    storageBucket: 'finyx-99abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALBC0AHsc09YPSAEz9H9NLMSeQO2Eekds',
    appId: '1:63018309040:ios:4b57ce9dfcaaaaff007275',
    messagingSenderId: '63018309040',
    projectId: 'finyx-99abc',
    storageBucket: 'finyx-99abc.firebasestorage.app',
    iosBundleId: 'com.example.finyxMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALBC0AHsc09YPSAEz9H9NLMSeQO2Eekds',
    appId: '1:63018309040:ios:4b57ce9dfcaaaaff007275',
    messagingSenderId: '63018309040',
    projectId: 'finyx-99abc',
    storageBucket: 'finyx-99abc.firebasestorage.app',
    iosBundleId: 'com.example.finyxMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFNk8Xo4akgLh7ypLy4Gy10eyO77BUR-Y',
    appId: '1:63018309040:web:33ee0e351c89df8a007275',
    messagingSenderId: '63018309040',
    projectId: 'finyx-99abc',
    authDomain: 'finyx-99abc.firebaseapp.com',
    storageBucket: 'finyx-99abc.firebasestorage.app',
    measurementId: 'G-HG0MT4KSP9',
  );
}
